---

- name: "Add the user {{ user }}"
  user:
    name: "{{ user }}"

- name: "Create {{ document_root }} directory"
  file:
    path: "{{ document_root }}"
    group: "{{ user }}"
    owner: "{{ user }}"
    state: directory

- import_tasks: packages-ubuntu.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- import_tasks: packages-centos.yml
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"

#- import_tasks: ioncube.yml
#  become: yes

- name: "Create /etc/caddy directory"
  file:
    path: "/etc/caddy"
    state: directory

- name: generate caddy config file
  template:
    src: Caddyfile.j2
    dest: "/etc/caddy/Caddyfile"
  notify:
     - restart caddy

- name: "Create a new database with name {{ db_name }}"
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: "Create mysql user {{ db_user }}"
  mysql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
