- name: Ubuntu - Install software-properties-common package
  apt:
    name: software-properties-common
    update_cache: yes
    state: present

- name: Ubuntu - Add PPA repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Ubuntu - Add Caddy apt key.
  apt_key:
    url: "https://dl.cloudsmith.io/public/caddy/stable/gpg.key"
    id: 65760C51EDEA2017CEA2CA15155B6D79CA56EA34
    state: present
  register: add_repository_key
#  ignore_errors: "{{ caddy_apt_ignore_key_error }}"

- name: Ubuntu - Add Caddy repository.
  apt_repository:
    repo: "deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    state: present
    update_cache: true
  
- name: Ubuntu - Install packages
  apt:
    state: present
    pkg:
    - python3-mysqldb
    - cron
    - curl   
    - mariadb-server
    - caddy
    - php{{ php_version }}-fpm
    - php{{ php_version }}-tidy
    - php{{ php_version }}-mysql
    - php{{ php_version }}-gd
    - php{{ php_version }}-mbstring

- name: Ubuntu - Make sure a service unit is running
  systemd:
    state: started
    name: "{{ item }}"
  with_items:
     - mariadb
     - cron
     - php{{ php_version }}-fpm
     - caddy

- name: Ubuntu - generate php-fpm config file
  template:
    src: fpm-www.conf.j2
    dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
  notify:
     - restart php-fpm-ubuntu  